services:
  main-database:
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:10000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: security
    restart: unless-stopped
  security-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security-service
    environment:
      DB_HOST: main-database
      DB_PORT: 5432
      DB_NAME: security
      DB_USERNAME: user
      DB_PASSWORD: user
    ports:
      - "10001:8080"
    restart: unless-stopped