spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:security}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
    path: /security-api
  swagger-ui:
    path: /swagger
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    enabled: false