spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10000}/${DB_NAME:event-space}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
springdoc:
  api-docs:
    enabled: true
    path: /security-api
  swagger-ui:
    path: /swagger
jwt:
  secret: ${JWT_SECRET:here_is_the_jwt_secret_override_it_please!}

eureka:
  client:
    enabled: false