CREATE SCHEMA user_unit

CREATE TABLE user_unit.refresh_token
(
    refresh_token   VARCHAR(255) NOT NULL,
    user_id         BIGINT,
    issue_date      TIMESTAMP WITHOUT TIME ZONE,
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (refresh_token)
);

CREATE TABLE user_unit.users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(64)                             NOT NULL,
    first_name   VARCHAR(64),
    last_name    VARCHAR(64),
    password     VARCHAR(80),
    phone_number VARCHAR(15),
    role         SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_unit.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_unit.refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_unit.users (id);