CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(64)                             NOT NULL,
    email        VARCHAR(64)                             NOT NULL,
    first_name   VARCHAR(64)                             NOT NULL,
    last_name    VARCHAR(64),
    password     VARCHAR(80),
    phone_number VARCHAR(15)                             NOT NULL,
    role         SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);